version: '3.8'
name: 'url_shortener_db'
volumes:
  url_shortener_data:
    driver: local
services:
  url_shortener_db:
    container_name: url_shortener_db
    image: postgres:latest
    restart: always
    env_file:
        - path: .env
    ports:
      - 5432:5432
    volumes:
      - url_shortener_data:/var/lib/postgresql/data
  url_shortener_api:
    container_name: url_shortener_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - path: .env
    depends_on:
      - url_shortener_db
    restart: always
