[project]
name = "url-shortener"
version = "0.1.0"
description = "A simple URL shortener API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]
